name: CI
env: 
  pem: ${{ secrets.pem }}
on: 
  workflow_dispatch:
jobs:
  Pack:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: |
          mkdir build
          mkdir crx
          mkdir yacd
      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          path: crx
      - name: Checkout Yacd
        uses: actions/checkout@v2.7.0
        with:
          repository: "haishanh/yacd"
          ref: gh-pages
          path: yacd
      - run: |
          rm -rf ./crx/.git
          rm -rf ./yacd/.git
          mv ./crx/* ./build
          mv ./yacd/* ./build
      - run: |
          echo "$pem" > yacd.pem
          chrome.exe --pack-extension="./build" --pack-extension-key="yacd.pem"
      - uses: actions/upload-artifact@latest
        with:
          name: build
          path: build
