name: CI
env: 
  pem: ${{ secrets.pem }}
on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  Pack:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: |
          mkdir build
          mkdir crx
          mkdir yacd
      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          path: crx
      - name: Checkout Yacd
        uses: actions/checkout@v2.7.0
        with:
          repository: "haishanh/yacd"
          ref: gh-pages
          path: yacd
      - run: |
          rm -rf ./crx/.git
          rm -rf ./yacd/.git
          mv ./crx/* ./build
          mv ./yacd/* ./build
          rm ./build/_*
      - run: |
          echo "$pem" > yacd.pem
          chrome --pack-extension=build --pack-extension-key=yacd.pem
          mv build.crx yacd.crx
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: build
          path: build
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: crx
          path: "*.crx"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: auto
          title: "Automatic Build"
          files: |
            *.crx
